# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\disign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.enterBtn.setGeometry(QtCore.QRect(280, 190, 161, 31))
        self.enterBtn.setObjectName("enterBtn")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(280, 270, 161, 31))
        self.saveButton.setObjectName("saveButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(280, 310, 161, 31))
        self.startButton.setObjectName("startButton")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(120, 50, 631, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setObjectName("errorLabel")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(280, 230, 161, 31))
        self.addButton.setObjectName("addButton")
        self.inareaBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.inareaBtn.setGeometry(QtCore.QRect(260, 380, 201, 17))
        self.inareaBtn.setObjectName("inareaBtn")
        self.outareabtn = QtWidgets.QRadioButton(self.centralwidget)
        self.outareabtn.setGeometry(QtCore.QRect(260, 420, 201, 17))
        self.outareabtn.setObjectName("outareabtn")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(540, 160, 191, 17))
        self.checkBox.setObjectName("checkBox")
        self.dwdmBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dwdmBtn.setGeometry(QtCore.QRect(550, 190, 161, 31))
        self.dwdmBtn.setObjectName("dwdmBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enterBtn.setText(_translate("MainWindow", "Открыть граф"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.startButton.setText(_translate("MainWindow", "Запуск"))
        self.errorLabel.setText(_translate("MainWindow", "-"))
        self.addButton.setText(_translate("MainWindow", "Открыть пути"))
        self.inareaBtn.setText(_translate("MainWindow", "Приоритет на путь внутри региона"))
        self.outareabtn.setText(_translate("MainWindow", "Приоритет на путь вне региона"))
        self.checkBox.setText(_translate("MainWindow", "C учётом таблицы Ребра DWDM"))
        self.dwdmBtn.setText(_translate("MainWindow", "Открыть граф DWDM"))
